name: new_windows
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5
  http: ^0.13.6
  bloc:
  flutter_bloc: 8.1.2
  dio: ^5.1.2
  rflutter_alert: ^2.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_color_generator: ^1.1.0
  dialog_flowtter: ^0.3.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
flutter_native_splash:
  image: assets/log.png
  color: "#ffffff"
  android: true
  ios: true
  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/img.png
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/welcome/
    - assets/doc/
